---

#
# This file contains configuration flags to customize this site
#

# Name of the site (displayed in the content)
name: Blue Husky Studios
# Name of the site (displayed in the tab)
title: Blue Husky Studios

# Short bio or description (in share links)
description: Blue Husky Studios is an indie entertainment brand. We make art, develop software, and review stuff!

authors:
    -
        name: Ben Leggiero
        shortName: Ben
        tagline-html: Developer&emsp;|&emsp;Designer
        avatar: >
            https://www.gravatar.com/avatar/2f4691f7a1c9d3192fe843a164a27535?s=280px

        social:
            blog: https://BenLeggiero.blog
            calendar: https://BenLeggiero.me/Calendar
            email: BenLeggiero@Gmail.com
            github-suffix:
                this: BenLeggiero/resumes
                personal: BenLeggiero
                big-projects: BlueHuskyStudios
                utilities: RougeWare
            linkedin-username: ben-leggiero
            mastodon: https://Mastodon.Social/@BenLeggiero
            phone:
                display-html: +1&nbsp;(470) BEN&nbsp;C&nbsp;LEG
                disambiguation: 236-2534
                just-numbers: 14702362534
            stackoverflow-suffix: story/benleggiero
            twitter-username: BenLeggiero
            website: https://BenLeggiero.me

dates:
    -
        originally-written: 2012-11-29
        newest:
            web: 2019-11-18


# This website URL
# Used for Sitemap.xml and the RSS feed
url: https://BHStudios.org

timezone: America/Denver


# Low-level config lines #


permalink: /:title

# The release of Jekyll that this site is using
version: v3.8.5

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
    style: :expanded  # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
    - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
    - jekyll-feed  # Create an Atom feed using the official Jekyll feed gem
    - jekyll-archives
    - jekyll-redirect-from  # Allow multiple names for a page

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - CNAME
